name: Sayan's Daily Activity Booster

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

jobs:
  update-text:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Activity Log
        run: |
          export TZ="Asia/Kolkata"
          echo "✨ Profile Active | IST: $(date +'%Y-%m-%d %H:%M:%S') | Session: $RANDOM" >> last_activity.txt

      - name: Commit & Push as Sayan
        run: |
          export TZ="Asia/Kolkata"
          git config --global user.name "kajju027"
          git config --global user.email "kajju3864@gmail.com"
          
          git add last_activity.txt
          git commit -m "Activity Log Updated ✅ [$(date +'%d-%m-%Y %H:%M')] #$RANDOM" --allow-empty
          git push
          
